# .github/workflows/review_time_and_assigner.yaml
name: Estimate Review Time and Assign Reviewer

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  pr_monitoring:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Estimate review time
      id: review_time
      run: |
        # Count the number of changed files in the pull request
        CHANGED_FILES=$(jq '.files | length' < $GITHUB_EVENT_PATH)
        # Assuming 2 minutes per file for review time
        REVIEW_TIME=$((CHANGED_FILES * 2))
        echo "Estimated review time: $REVIEW_TIME minutes"
        echo "::set-output name=review_time::$REVIEW_TIME"

    - name: Assign reviewer based on estimated time
      run: |
        # Simple logic to assign reviewers based on review time
        if [ "${{ steps.review_time.outputs.review_time }}" -le 10 ]; then
          REVIEWER="reviewer1"  # Replace with actual GitHub username
        elif [ "${{ steps.review_time.outputs.review_time }}" -le 20 ]; then
          REVIEWER="reviewer2"  # Replace with actual GitHub username
        else
          REVIEWER="reviewer3"  # Replace with actual GitHub username
        fi
        echo "Assigning reviewer: $REVIEWER"

        # Use GitHub CLI to assign the reviewer
        gh pr review --add $REVIEWER ${{ github.event.pull_request.number }}
